create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name text not null,
    username text not null unique,
    contact text,
    email text,
    address text,
    password text not null,
    role text not null default 'user'
);

create table if not exists public.food_posts (
    id bigint generated by default as identity primary key,
    owner_id bigint references public.users(id) on delete set null,
    title text not null,
    food_type text not null,
    description text not null,
    quantity text not null,
    location text not null,
    available_date date not null,
    available_time text not null,
    sharer_name text not null,
    contact_details text not null,
    image text,
    claimed boolean not null default false,
    claimer_name text,
    claimer_contact text,
    claimer_id bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

alter table public.food_posts
add column if not exists food_type text;

create table if not exists public.food_requests (
    id bigint generated by default as identity primary key,
    post_id bigint references public.food_posts(id) on delete cascade,
    user_id bigint references public.users(id) on delete cascade,
    title text not null,
    location text not null,
    pickup_time text not null,
    sharer_name text not null,
    sharer_contact text not null,
    status text not null default 'Pending pickup',
    image text,
    created_at timestamptz not null default now()
);

create index if not exists idx_users_username on public.users(username);
create index if not exists idx_food_posts_owner_id on public.food_posts(owner_id);
create index if not exists idx_food_posts_claimed on public.food_posts(claimed);
create index if not exists idx_food_requests_user_id on public.food_requests(user_id);
create index if not exists idx_food_requests_post_id on public.food_requests(post_id);

alter table public.users enable row level security;
alter table public.food_posts enable row level security;
alter table public.food_requests enable row level security;

drop policy if exists "anon can read users" on public.users;
drop policy if exists "anon can insert users" on public.users;
drop policy if exists "anon can update users" on public.users;

create policy "anon can read users"
on public.users
for select
to anon
using (true);

create policy "anon can insert users"
on public.users
for insert
to anon
with check (true);

create policy "anon can update users"
on public.users
for update
to anon
using (true)
with check (true);

drop policy if exists "anon can read food_posts" on public.food_posts;
drop policy if exists "anon can insert food_posts" on public.food_posts;
drop policy if exists "anon can update food_posts" on public.food_posts;

create policy "anon can read food_posts"
on public.food_posts
for select
to anon
using (true);

create policy "anon can insert food_posts"
on public.food_posts
for insert
to anon
with check (true);

create policy "anon can update food_posts"
on public.food_posts
for update
to anon
using (true)
with check (true);

drop policy if exists "anon can read food_requests" on public.food_requests;
drop policy if exists "anon can insert food_requests" on public.food_requests;
drop policy if exists "anon can update food_requests" on public.food_requests;

create policy "anon can read food_requests"
on public.food_requests
for select
to anon
using (true);

create policy "anon can insert food_requests"
on public.food_requests
for insert
to anon
with check (true);

create policy "anon can update food_requests"
on public.food_requests
for update
to anon
using (true)
with check (true);
